# Generated by Django 5.1.4 on 2025-01-04 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30)),
                ('password', models.TextField(max_length=50)),
                ('password1', models.TextField(max_length=50)),
            ],
        ),
    ]
