# Generated by Django 5.1.4 on 2025-01-05 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_fname_signup_first_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='signup',
        ),
    ]
