# Generated by Django 5.1.4 on 2025-01-06 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialization',
            name='program',
        ),
        migrations.RemoveField(
            model_name='studymaterial',
            name='specialization',
        ),
        migrations.DeleteModel(
            name='Program',
        ),
        migrations.DeleteModel(
            name='Specialization',
        ),
        migrations.DeleteModel(
            name='StudyMaterial',
        ),
    ]
