# Generated by Django 5.1.4 on 2025-01-06 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='standard',
            old_name='std',
            new_name='name',
        ),
    ]
