# Generated by Django 5.1.4 on 2025-01-06 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_std_standard_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chapters',
            new_name='Chapter',
        ),
        migrations.RenameField(
            model_name='chapter',
            old_name='standard',
            new_name='std',
        ),
        migrations.RenameField(
            model_name='standard',
            old_name='name',
            new_name='std',
        ),
    ]
