# Generated by Django 5.1.4 on 2025-01-06 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_standard_chapter_std_rename_name_standard_std_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studymaterial',
            old_name='chapters',
            new_name='chapter',
        ),
    ]
