# Generated by Django 5.1.4 on 2025-01-10 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_post_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='myphoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='about_photos/')),
            ],
        ),
    ]
