# Generated by Django 5.1.4 on 2025-01-10 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_myphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aboutinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='about_photos/')),
                ('info', models.TextField()),
                ('achievement', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='myphoto',
        ),
    ]
