# Generated by Django 5.1.4 on 2025-01-10 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_aboutinfo_delete_myphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutinfo',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
