# Generated by Django 5.1.4 on 2025-01-10 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_myphoto_delete_aboutinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='myinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField()),
            ],
        ),
    ]
