# Generated by Django 5.1.4 on 2025-01-20 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_mycontact_myemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycontact',
            name='contact',
            field=models.CharField(max_length=14),
        ),
    ]
