# Generated by Django 5.1.4 on 2025-01-20 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_insta_tele_yt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='insta',
        ),
        migrations.DeleteModel(
            name='Tele',
        ),
        migrations.DeleteModel(
            name='yt',
        ),
    ]
