# Generated by Django 5.1.4 on 2025-01-22 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_quiz_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
