# Generated by Django 5.1.4 on 2025-01-22 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_remove_quiz_time_quiz_time_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='time_limit',
            field=models.IntegerField(default=1),
        ),
    ]
